export const SITE = {
  url: 'https://thefieldandfarm.com',
  name: 'The Field & Farm',
  description:
    'Practical guides for gardeners, homesteaders, and small farmers: growing vegetables, raising livestock, soil and compost, food preservation, and farm business. Fact-first, current, practical.',
};

export const CATEGORIES = [
  {
    id: 'vegetables',
    name: 'Vegetables & Garden Crops',
    verticals: [
      { id: 'root-vegetables', name: 'Root Vegetables' },
      { id: 'leafy-greens', name: 'Leafy Greens' },
      { id: 'brassicas', name: 'Brassicas' },
      { id: 'tomatoes-peppers', name: 'Tomatoes & Peppers' },
      { id: 'squash-cucurbits', name: 'Squash & Cucurbits' },
      { id: 'beans-legumes', name: 'Beans & Legumes' },
      { id: 'alliums', name: 'Onions, Garlic & Alliums' },
      { id: 'corn-grains', name: 'Corn & Grains' },
      { id: 'eggplant-nightshades', name: 'Eggplant & Nightshades' },
      { id: 'microgreens-sprouts', name: 'Microgreens & Sprouts' },
      { id: 'heirloom-exotic', name: 'Heirloom & Exotic Vegetables' },
      { id: 'winter-vegetables', name: 'Winter Vegetables' },
    ],
  },
  {
    id: 'methods',
    name: 'Gardening Methods & Systems',
    verticals: [
      { id: 'raised-bed', name: 'Raised Bed Gardening' },
      { id: 'container-gardening', name: 'Container Gardening' },
      { id: 'square-foot', name: 'Square Foot Gardening' },
      { id: 'vertical-gardening', name: 'Vertical Gardening' },
      { id: 'indoor-gardening', name: 'Indoor Gardening' },
      { id: 'greenhouse', name: 'Greenhouse Growing' },
      { id: 'hydroponics', name: 'Hydroponics & Aquaponics' },
      { id: 'no-till', name: 'No-Till Gardening' },
      { id: 'companion-planting', name: 'Companion Planting' },
      { id: 'succession-planting', name: 'Succession Planting' },
      { id: 'seed-starting', name: 'Seed Starting' },
      { id: 'season-extension', name: 'Season Extension' },
    ],
  },
  {
    id: 'soil',
    name: 'Soil, Compost & Fertilizers',
    verticals: [
      { id: 'soil-health', name: 'Soil Health & Testing' },
      { id: 'composting', name: 'Composting' },
      { id: 'worm-composting', name: 'Worm Composting' },
      { id: 'fertilizers', name: 'Fertilizers & Plant Feeding' },
      { id: 'soil-amendments', name: 'Organic Soil Amendments' },
      { id: 'mulching-weeds', name: 'Mulching & Weed Control' },
      { id: 'irrigation', name: 'Irrigation & Water Management' },
      { id: 'rainwater', name: 'Rainwater Harvesting' },
    ],
  },
  {
    id: 'fruit-herbs',
    name: 'Fruit, Herbs & Specialty Crops',
    verticals: [
      { id: 'berries', name: 'Berries & Small Fruit' },
      { id: 'tree-fruit', name: 'Tree Fruit & Orchards' },
      { id: 'culinary-herbs', name: 'Culinary Herbs' },
      { id: 'medicinal-herbs', name: 'Medicinal Herbs' },
      { id: 'mushrooms', name: 'Mushrooms' },
      { id: 'cut-flowers', name: 'Cut Flowers' },
      { id: 'grapes-vines', name: 'Grapes & Vine Crops' },
      { id: 'citrus', name: 'Citrus & Warm-Climate Fruit' },
      { id: 'herbal-remedies', name: 'Herbal Remedies & Tinctures' },
    ],
  },
  {
    id: 'plant-care',
    name: 'Plant Care & Problem Solving',
    verticals: [
      { id: 'garden-pests', name: 'Garden Pests' },
      { id: 'plant-diseases', name: 'Plant Diseases' },
      { id: 'nutrient-deficiencies', name: 'Nutrient Deficiencies' },
      { id: 'weed-management', name: 'Weed Management' },
      { id: 'pruning-training', name: 'Pruning & Training' },
      { id: 'pollinators', name: 'Pollinators & Beneficial Insects' },
      { id: 'wildlife-control', name: 'Wildlife & Predator Control' },
      { id: 'propagation', name: 'Plant Propagation' },
    ],
  },
  {
    id: 'livestock',
    name: 'Livestock & Poultry',
    verticals: [
      { id: 'chickens', name: 'Backyard Chickens' },
      { id: 'ducks-waterfowl', name: 'Ducks & Waterfowl' },
      { id: 'turkeys-game-birds', name: 'Turkeys & Game Birds' },
      { id: 'goats', name: 'Goats' },
      { id: 'cattle', name: 'Cattle' },
      { id: 'pigs', name: 'Pigs' },
      { id: 'sheep-wool', name: 'Sheep & Wool' },
      { id: 'beekeeping', name: 'Beekeeping' },
      { id: 'rabbits', name: 'Rabbits & Small Animals' },
      { id: 'alpacas-llamas', name: 'Alpacas & Llamas' },
      { id: 'livestock-health', name: 'Livestock Health & Care' },
      { id: 'breeding-incubation', name: 'Breeding & Incubation' },
    ],
  },
  {
    id: 'homesteading',
    name: 'Homesteading & Food Preservation',
    verticals: [
      { id: 'canning', name: 'Canning & Preserving' },
      { id: 'fermenting-pickling', name: 'Fermenting & Pickling' },
      { id: 'dehydrating-freezing', name: 'Dehydrating & Freezing' },
      { id: 'sourdough-baking', name: 'Sourdough & Baking' },
      { id: 'cheese-dairy', name: 'Cheese Making & Dairy' },
      { id: 'meat-processing', name: 'Meat Processing & Curing' },
      { id: 'seed-saving', name: 'Seed Saving' },
      { id: 'root-cellars', name: 'Root Cellars & Storage' },
      { id: 'soap-candles', name: 'Soap & Candle Making' },
      { id: 'foraging', name: 'Foraging & Wild Edibles' },
      { id: 'maple-syrup', name: 'Maple Syrup & Specialty Foods' },
    ],
  },
  {
    id: 'farm-business',
    name: 'Farm Business, Equipment & Rural Living',
    verticals: [
      { id: 'tractors', name: 'Tractors & Machinery' },
      { id: 'hand-tools', name: 'Hand Tools & Equipment' },
      { id: 'fencing-structures', name: 'Fencing & Structures' },
      { id: 'business-accounting', name: 'Farm Business & Accounting' },
      { id: 'insurance-compliance', name: 'Farm Insurance & Compliance' },
      { id: 'farmers-markets', name: 'Farmers Markets & Direct Sales' },
      { id: 'csa-u-pick', name: 'CSA & U-Pick' },
      { id: 'agritourism', name: 'Agritourism' },
      { id: 'grants-usda', name: 'Grants & USDA Programs' },
      { id: 'land-property', name: 'Land & Property' },
      { id: 'off-grid', name: 'Off-Grid & Rural Living' },
      { id: 'permaculture', name: 'Permaculture & Regenerative' },
    ],
  },
];

export const VERTICALS = CATEGORIES.flatMap((c) => c.verticals);
